# Carv Verifier Node Configuration
# Based on official Carv repository: https://github.com/carv-protocol/verifier

chain:
  chain_id: 42161
  chain_name: "arbitrum"
  rpc_url: "https://arb1.arbitrum.io/rpc"
  start_block: 0
  offset_block: 14400 # arbitrum block time: 0.25 sec. An offset of 14400 starts fetching blocks from 1 hours ago.

contract:
  addr: "0xFFbB58c8370f99b2ae619328D6B99D77Fef190Cb"
  tee_addr: "0x7f57004E08ef1702b2b88b87ae01a561ae10F10e"
  topic1: "0x89a3b784b99180438f3b2027aa89e97c3c3ed66e8dc78a555d7013b39caf1a89"
  topic2: "0x455929120054502ca2ea8194b26e7bb3acb631d30177f6881ffa70581abd4a13"

# Wallet configuration - Mode 1: plain text private key in config file
wallet:
  # wallet mode, by which way to pass the private key
  # 0: through startup parameters
  # 1: through plain text private key in config file
  # 2: through path and password of the keystore in config file
  mode: 1
  # plain text private key, needed when mode is 1
  private_key: "${CARV_PRIVATE_KEY}"
  # path of the keystore, needed when mode is 2
  keystore_path: ""
  # password of the keystore, needed when mode is 2
  keystore_password: ""
  reward_claimer_addr: "${CARV_REWARD_CLAIMER_ADDR:-0x0000000000000000000000000000000000000000}"
  commission_rate: 0

signature:
  domain_name: "ProtocolService"
  domain_version: "1.0.0"
  expired_time: 3600

gasless_service:
  url: "https://interface.carv.io"
